package com.bisu.entities;
// Generated Dec 26, 2017 11:32:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name="departments"
    ,catalog="bisu_db"
)
public class Departments  implements java.io.Serializable {


     private Integer id;
     private String description;
     private String head;
     private Set<Faculties> facultieses = new HashSet<Faculties>(0);
     private Set<Courses> courseses = new HashSet<Courses>(0);
     private String code;

    public Departments() {
    }

	
    public Departments(String description, String head) {
        this.description = description;
        this.head = head;
    }
    public Departments(String description, String head, Set<Faculties> facultieses, Set<Courses> courseses) {
       this.description = description;
       this.head = head;
       this.facultieses = facultieses;
       this.courseses = courseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    
    @Column(name="head", nullable=false)
    public String getHead() {
        return this.head;
    }
    
    public void setHead(String code) {
        this.code = code;
    }
    
    @Column(name="code", nullable=false , unique=true)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String head) {
        this.head = head;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set<Faculties> getFacultieses() {
        return this.facultieses;
    }
    
    public void setFacultieses(Set<Faculties> facultieses) {
        this.facultieses = facultieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departments")
    public Set<Courses> getCourseses() {
        return this.courseses;
    }
    
    public void setCourseses(Set<Courses> courseses) {
        this.courseses = courseses;
    }




}


