package com.bisu.entities;
// Generated Dec 26, 2017 11:32:06 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Faculties generated by hbm2java
 */
@Entity
@Table(name="faculties"
    ,catalog="bisu_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="faculty_id") 
)
public class Faculties  implements java.io.Serializable {


     private Integer id;
     private Departments departments;
     private Integer facultyId;
     private String firstname;
     private String lastname;
     private String middlename;
     private String designation;
     private String eligibility;
     private String specializationn;
     private String degreeEarned;
     private String postDegree;
     private String minLoad;
     private int maxLoad;

    public Faculties() {
    }

	
    public Faculties(String firstname, String lastname, String middlename, String designation, String eligibility, String specializationn, String degreeEarned, String postDegree, String minLoad, int maxLoad) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.middlename = middlename;
        this.designation = designation;
        this.eligibility = eligibility;
        this.specializationn = specializationn;
        this.degreeEarned = degreeEarned;
        this.postDegree = postDegree;
        this.minLoad = minLoad;
        this.maxLoad = maxLoad;
    }
    public Faculties(Departments departments, Integer facultyId, String firstname, String lastname, String middlename, String designation, String eligibility, String specializationn, String degreeEarned, String postDegree, String minLoad, int maxLoad) {
       this.departments = departments;
       this.facultyId = facultyId;
       this.firstname = firstname;
       this.lastname = lastname;
       this.middlename = middlename;
       this.designation = designation;
       this.eligibility = eligibility;
       this.specializationn = specializationn;
       this.degreeEarned = degreeEarned;
       this.postDegree = postDegree;
       this.minLoad = minLoad;
       this.maxLoad = maxLoad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

    
    @Column(name="faculty_id", unique=true)
    public Integer getFacultyId() {
        return this.facultyId;
    }
    
    public void setFacultyId(Integer facultyId) {
        this.facultyId = facultyId;
    }

    
    @Column(name="firstname", nullable=false)
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    
    @Column(name="lastname", nullable=false)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="middlename", nullable=false)
    public String getMiddlename() {
        return this.middlename;
    }
    
    public void setMiddlename(String middlename) {
        this.middlename = middlename;
    }

    
    @Column(name="designation", nullable=false)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="eligibility", nullable=false)
    public String getEligibility() {
        return this.eligibility;
    }
    
    public void setEligibility(String eligibility) {
        this.eligibility = eligibility;
    }

    
    @Column(name="specializationn", nullable=false)
    public String getSpecializationn() {
        return this.specializationn;
    }
    
    public void setSpecializationn(String specializationn) {
        this.specializationn = specializationn;
    }

    
    @Column(name="degree_earned", nullable=false)
    public String getDegreeEarned() {
        return this.degreeEarned;
    }
    
    public void setDegreeEarned(String degreeEarned) {
        this.degreeEarned = degreeEarned;
    }

    
    @Column(name="post_degree", nullable=false)
    public String getPostDegree() {
        return this.postDegree;
    }
    
    public void setPostDegree(String postDegree) {
        this.postDegree = postDegree;
    }

    
    @Column(name="min_load", nullable=false)
    public String getMinLoad() {
        return this.minLoad;
    }
    
    public void setMinLoad(String minLoad) {
        this.minLoad = minLoad;
    }

    
    @Column(name="max_load", nullable=false)
    public int getMaxLoad() {
        return this.maxLoad;
    }
    
    public void setMaxLoad(int maxLoad) {
        this.maxLoad = maxLoad;
    }




}


