package com.bisu.entities;
// Generated Dec 26, 2017 11:32:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subjects generated by hbm2java
 */
@Entity
@Table(name="subjects"
    ,catalog="bisu_db"
)
public class Subjects  implements java.io.Serializable {


     private Integer id;
     private String description;
     private Integer courseId;
     private short units;
     private Date lecHours;
     private Date labHours;
     private String type;
     private Set<SubjectPreRequisites> subjectPreRequisitesesForPreRequisiteId = new HashSet<SubjectPreRequisites>(0);
     private Set<SubjectPreRequisites> subjectPreRequisitesesForSubjectId = new HashSet<SubjectPreRequisites>(0);

    public Subjects() {
    }

	
    public Subjects(String description, short units, String type) {
        this.description = description;
        this.units = units;
        this.type = type;
    }
    public Subjects(String description, Integer courseId, short units, Date lecHours, Date labHours, String type, Set<SubjectPreRequisites> subjectPreRequisitesesForPreRequisiteId, Set<SubjectPreRequisites> subjectPreRequisitesesForSubjectId) {
       this.description = description;
       this.courseId = courseId;
       this.units = units;
       this.lecHours = lecHours;
       this.labHours = labHours;
       this.type = type;
       this.subjectPreRequisitesesForPreRequisiteId = subjectPreRequisitesesForPreRequisiteId;
       this.subjectPreRequisitesesForSubjectId = subjectPreRequisitesesForSubjectId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="description", nullable=false)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="course_id")
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    
    @Column(name="units", nullable=false)
    public short getUnits() {
        return this.units;
    }
    
    public void setUnits(short units) {
        this.units = units;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="lec_hours", length=8)
    public Date getLecHours() {
        return this.lecHours;
    }
    
    public void setLecHours(Date lecHours) {
        this.lecHours = lecHours;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="lab_hours", length=8)
    public Date getLabHours() {
        return this.labHours;
    }
    
    public void setLabHours(Date labHours) {
        this.labHours = labHours;
    }

    
    @Column(name="type", nullable=false, length=8)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subjectsByPreRequisiteId")
    public Set<SubjectPreRequisites> getSubjectPreRequisitesesForPreRequisiteId() {
        return this.subjectPreRequisitesesForPreRequisiteId;
    }
    
    public void setSubjectPreRequisitesesForPreRequisiteId(Set<SubjectPreRequisites> subjectPreRequisitesesForPreRequisiteId) {
        this.subjectPreRequisitesesForPreRequisiteId = subjectPreRequisitesesForPreRequisiteId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subjectsBySubjectId")
    public Set<SubjectPreRequisites> getSubjectPreRequisitesesForSubjectId() {
        return this.subjectPreRequisitesesForSubjectId;
    }
    
    public void setSubjectPreRequisitesesForSubjectId(Set<SubjectPreRequisites> subjectPreRequisitesesForSubjectId) {
        this.subjectPreRequisitesesForSubjectId = subjectPreRequisitesesForSubjectId;
    }




}


