package com.bisu.entities;
// Generated Dec 26, 2017 11:32:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubjectPreRequisites generated by hbm2java
 */
@Entity
@Table(name="subject_pre_requisites"
    ,catalog="bisu_db"
)
public class SubjectPreRequisites  implements java.io.Serializable {


     private Integer id;
     private Subjects subjectsByPreRequisiteId;
     private Subjects subjectsBySubjectId;
     private Date createdAt;
     private Date updatedAt;

    public SubjectPreRequisites() {
    }

	
    public SubjectPreRequisites(Subjects subjectsBySubjectId) {
        this.subjectsBySubjectId = subjectsBySubjectId;
    }
    public SubjectPreRequisites(Subjects subjectsByPreRequisiteId, Subjects subjectsBySubjectId, Date createdAt, Date updatedAt) {
       this.subjectsByPreRequisiteId = subjectsByPreRequisiteId;
       this.subjectsBySubjectId = subjectsBySubjectId;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pre_requisite_id")
    public Subjects getSubjectsByPreRequisiteId() {
        return this.subjectsByPreRequisiteId;
    }
    
    public void setSubjectsByPreRequisiteId(Subjects subjectsByPreRequisiteId) {
        this.subjectsByPreRequisiteId = subjectsByPreRequisiteId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="subject_id", nullable=false)
    public Subjects getSubjectsBySubjectId() {
        return this.subjectsBySubjectId;
    }
    
    public void setSubjectsBySubjectId(Subjects subjectsBySubjectId) {
        this.subjectsBySubjectId = subjectsBySubjectId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_at", length=19)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_at", length=19)
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


