package com.bisu.entities;
// Generated Dec 29, 2017 2:25:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TeachersLoadings generated by hbm2java
 */
@Entity
@Table(name="teachers_loadings"
    ,catalog="bisu_db"
)
public class TeachersLoadings  implements java.io.Serializable {


     private Integer id;
     private int teacherId;
     private int subjectId;
     private Set<TeachersLoadingDetails> teachersLoadingDetailses = new HashSet<TeachersLoadingDetails>(0);

    public TeachersLoadings() {
    }

	
    public TeachersLoadings(int teacherId, int subjectId) {
        this.teacherId = teacherId;
        this.subjectId = subjectId;
    }
    public TeachersLoadings(int teacherId, int subjectId, Set<TeachersLoadingDetails> teachersLoadingDetailses) {
       this.teacherId = teacherId;
       this.subjectId = subjectId;
       this.teachersLoadingDetailses = teachersLoadingDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="teacher_id", nullable=false)
    public int getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }

    
    @Column(name="subject_id", nullable=false)
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="teachersLoadings")
    public Set<TeachersLoadingDetails> getTeachersLoadingDetailses() {
        return this.teachersLoadingDetailses;
    }
    
    public void setTeachersLoadingDetailses(Set<TeachersLoadingDetails> teachersLoadingDetailses) {
        this.teachersLoadingDetailses = teachersLoadingDetailses;
    }




}


