package com.bisu.entities;
// Generated Dec 29, 2017 2:25:44 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TeachersLoadingDetails generated by hbm2java
 */
@Entity
@Table(name="teachers_loading_details"
    ,catalog="bisu_db"
)
public class TeachersLoadingDetails  implements java.io.Serializable {


     private Integer id;
     private TeachersLoadings teachersLoadings;
     private int roomId;
     private Date hourStart;
     private Date hourEnd;
     private boolean m;
     private boolean t;
     private boolean w;
     private boolean th;
     private boolean f;

    public TeachersLoadingDetails() {
    }

	
    public TeachersLoadingDetails(TeachersLoadings teachersLoadings, int roomId, boolean m, boolean t, boolean w, boolean th, boolean f) {
        this.teachersLoadings = teachersLoadings;
        this.roomId = roomId;
        this.m = m;
        this.t = t;
        this.w = w;
        this.th = th;
        this.f = f;
    }
    public TeachersLoadingDetails(TeachersLoadings teachersLoadings, int roomId, Date hourStart, Date hourEnd, boolean m, boolean t, boolean w, boolean th, boolean f) {
       this.teachersLoadings = teachersLoadings;
       this.roomId = roomId;
       this.hourStart = hourStart;
       this.hourEnd = hourEnd;
       this.m = m;
       this.t = t;
       this.w = w;
       this.th = th;
       this.f = f;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="loading_id", nullable=false)
    public TeachersLoadings getTeachersLoadings() {
        return this.teachersLoadings;
    }
    
    public void setTeachersLoadings(TeachersLoadings teachersLoadings) {
        this.teachersLoadings = teachersLoadings;
    }

    
    @Column(name="room_id", nullable=false)
    public int getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(int roomId) {
        this.roomId = roomId;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hour_start", length=8)
    public Date getHourStart() {
        return this.hourStart;
    }
    
    public void setHourStart(Date hourStart) {
        this.hourStart = hourStart;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="hour_end", length=8)
    public Date getHourEnd() {
        return this.hourEnd;
    }
    
    public void setHourEnd(Date hourEnd) {
        this.hourEnd = hourEnd;
    }

    
    @Column(name="M", nullable=false)
    public boolean isM() {
        return this.m;
    }
    
    public void setM(boolean m) {
        this.m = m;
    }

    
    @Column(name="T", nullable=false)
    public boolean isT() {
        return this.t;
    }
    
    public void setT(boolean t) {
        this.t = t;
    }

    
    @Column(name="W", nullable=false)
    public boolean isW() {
        return this.w;
    }
    
    public void setW(boolean w) {
        this.w = w;
    }

    
    @Column(name="Th", nullable=false)
    public boolean isTh() {
        return this.th;
    }
    
    public void setTh(boolean th) {
        this.th = th;
    }

    
    @Column(name="F", nullable=false)
    public boolean isF() {
        return this.f;
    }
    
    public void setF(boolean f) {
        this.f = f;
    }




}


